In [6]:
import numpy
import pandas
import matplotlib.pyplot
z=(4,4)
a=numpy.ones(z)
print(a)

a*=5
print(a)

a= a.reshape((2, 8))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]


In [20]:
import numpy
import pandas
import matplotlib.pyplot
df = pandas.DataFrame()
df.insert(0,'Число',(range(1,11)))
df.insert(1,'Квадрат',df['Число']*df['Число'])
df_2=df.loc[df['Число']%2==0]
df_2=df_2.drop(['Число'], axis='columns')

print(df_2)

   Квадрат
1        4
3       16
5       36
7       64
9      100


In [21]:
import numpy
import pandas as pd
import matplotlib.pyplot
df=pd.read_csv('winequality-white.csv', delimiter=';')
df=df.loc[df['residual sugar']<1]
df=df[['density','pH']]
df=df.iloc[df.index%2==0]
print(df)

      density    pH
54    0.99300  3.05
172   0.99020  3.03
372   0.99340  3.34
1164  0.99280  3.07
1166  0.99270  3.23
1322  0.99200  3.54
1340  0.99220  3.27
1366  0.99140  3.25
1486  0.99320  3.30
2418  0.99274  3.16
2468  0.99155  3.25
2512  0.99112  3.28
2754  0.98985  3.13
2888  0.99180  3.04
2898  0.99104  2.99
2904  0.99114  3.31
2934  0.99215  3.30
2936  0.99218  3.30
2956  0.99026  2.80
2968  0.99038  2.93
2970  0.99038  2.93
2996  0.98942  3.11
3136  0.99026  3.50
3170  0.99126  3.02
3212  0.99033  3.25
3526  0.98984  3.01
3554  0.99062  2.92
3626  0.99048  3.21
3924  0.99249  2.95
4106  0.99119  3.16
4682  0.98990  3.11
4804  0.98934  3.24
4878  0.99234  3.24
